#!/bin/sh
source $GAAMPSCRIPTS/routines

cp $GAAMPRUN/230-qm_1d_scan/mol.prm .
cp $GAAMPRUN/230-qm_1d_scan/mol.xpsf .
cp $GAAMPRUN/230-qm_1d_scan/tor-1D-idx-*.dat .
cp $GAAMPRUN/230-qm_1d_scan/soft-dih-list.txt .

Gexe 1d-fitting

if [ "$NumTorsion" > 1 ]; then
  rm -Rf saved-para.dat
  touch saved-para.dat
  IdxTor=1
  while [  $IdxTor -le $NumTorsion ]; do
    head -n 1 torsion-para-${IdxTor}.dat >> saved-para.dat
    let IdxTor=IdxTor+1
  done
else
  head -n 1 torsion-para-1.dat > saved-para.dat
fi

### copying files to results
cp *dat $GAAMPRUN/results

$GAAMPSCRIPTS/plot-1d-result-and-org.sh
cp *png $GAAMPRUN/results


if [ "$WaterFit" -eq 0 ] && [ "$TorsionFitting" -lt "$MaxTorsion" ]; then ## end of additive gaamp 
    cp ../120-fit_esp/mol-esp.rtf mol-tor.rtf
    cp ../110-esp/mol-opt.crd .
    Gexe update-tor-para > update-tor-para.log
    cp mol-*m.pdb ../result/
    cp mol-tor.rtf ../result/mol-tor.rtf
    cp mol.prm ../result/mol-tor.prm
    cp mol.xpsf ../result/mol-tor.xpsf	
fi



exit 0
